# Generated by Django 4.0.2 on 2022-02-13 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('web_address', models.URLField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('do_you_like_working', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.baseuser',),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.baseuser',),
        ),
    ]
