# Generated by Django 4.0.2 on 2022-02-13 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.basemodel')),
                ('comment', models.TextField()),
                ('star', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('From_coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comment', to='app_accounts.candidate')),
                ('to_coment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_accounts.reviewer')),
            ],
            bases=('base_app.basemodel',),
        ),
    ]
